routes/web.php
<?php

Route::get('/','HomeController@index')->name('homepage');
//Route::get('/all-category','MainController@getCategories');
//Route::get('/all-brand','MainController@getBrands');
//Route::get('/featured-product','MainController@getFeaturedProducts');
//Route::get('/new-product','MainController@getNewProducts');
//Route::get('/category/{id}','MainController@getCatProducts');
//Route::get('/product-details/{id}','MainController@getProductDetails');

//Route::post('/search-checkbox','MainController@getProductCheckbox');
//Route::post('/search-product','MainController@getProductSearch');

//Route::get('/product-comment/{productId}','MainController@getProductComment');
//Route::post('/product-comment','MainController@productComment');

//Route::post('/add-cart','CartController@addToCart');
//Route::post('/delete-cart','CartController@deleteCart');
//Route::post('/update-cart','CartController@updateCart');
//Route::get('/all-cart','CartController@allCart');
//Route::get('/count-cart','CartController@countCart');

//Route::post('/user-register','CustomerController@register');
//Route::post('/user-login','CustomerController@login');
//Route::get('/user-logout','CustomerController@logout');
//Route::get('/customer-session','CustomerController@sessionData');

//Route::post('/shipping-info','OrderController@shippingInfo');
//Route::post('/confirm-order','OrderController@confirmOrder');

//Route::get('stripe', 'OrderController@stripe');
//Route::post('stripe', 'OrderController@stripePost')->name('stripe.post');

Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix'=>'admin','namespace'=>'Backend', 'middleware'=>'auth'], function (){
    //category
    Route::get('/category','CategoryController@index')->name('admin.category');
    Route::get('/category/getTableData','CategoryController@get')->name('admin.category.getTableData');
    Route::get('/category/edit/{id}','CategoryController@edit')->name('admin.category.getEditData');
    Route::post('/category/inlineedit','CategoryController@inlineEdit')->name('admin.category.inlineEdit');
    Route::post('/category','CategoryController@create');
    Route::post('/category/update','CategoryController@update')->name('admin.category.update');
    Route::get('/category/delete/{id}','CategoryController@delete')->name('admin.category.delete');
    Route::get('/category/publish/{id}','CategoryController@publish')->name('category.publish');
    Route::get('/category/unpublish/{id}','CategoryController@unpublish')->name('category.unpublish');

    //brand
    Route::get('/brand','BrandController@index')->name('admin.brand');
    Route::post('/brand','BrandController@create');
    Route::post('/brand/update/{id}','BrandController@update')->name('admin.brand.update');
    Route::get('/brand/delete/{id}','BrandController@delete')->name('admin.brand.delete');
    Route::get('/brand/publish/{id}','BrandController@publish')->name('brand.publish');
    Route::get('/brand/unpublish/{id}','BrandController@unpublish')->name('brand.unpublish');

    //product
    Route::resource('product', 'ProductController');

    //order
    Route::get('/order','OrderController@index')->name('admin.order');
    Route::get('/order/details/{id}','OrderController@viewOrderDetails')->name('view-order-details');
    Route::get('/order/invoice/{id}','OrderController@orderInvoice')->name('order.invoice');
    Route::get('/order/export-pdf/{id}','OrderController@orderExportPdf')->name('order.export.pdf');

    //user
    Route::get('/user','UserController@index')->name('admin.user');
    Route::post('/user','UserController@create');

});


//Route::get('{path}','MainController@index')->where( 'path', '.*' );

app/Http/Controllers/Backend/ProductController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Auth;
use App\Model\Product;
use App\Model\Category;
use App\Model\Brand;
use DB;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //$product = Product::all();
        $product = DB::table('products')
            ->join('categories','products.cat_id', '=', 'categories.id')
            ->join('brands','products.brand_id', '=', 'brands.id')
            ->join('users','products.uploaded_by', '=', 'users.id')
            ->select('products.*','categories.cat_name','brands.brand_name','users.name')
            ->get();

            //dd($product);
        $category = Category::where('cat_status', 1)->get();
        $brand = Brand::where('brand_status', 1)->get();

        return view('admin.product.product',[
            'product'=>$product,
            'category'=>$category,
            'brand'=>$brand,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $product = new Product();
        $imageUrl = '';
        if ($file = $request->file('product_image')) {
            $fileName = date("YmdHis")."_".$file->getClientOriginalName();
            $directory = 'admin/images/product_images/';
            $imageUrl = $directory.$fileName;
            $file->move($directory, $fileName);
            $product->image = $imageUrl;
        }
        if ($request->file('gallery_image')) {
            foreach ($request->file('gallery_image') as $image) {
                $fileName = $image->getClientOriginalName();
                $directory = 'admin/images/product_images/';
                $g_imageUrl = $directory.$fileName;
                $image->move($directory, $fileName);
                $data[] = $g_imageUrl;
            }
            $product->gallery_image = json_encode($data);
        }
        $product->cat_id = $request->cat_id;
        $product->brand_id = $request->brand_id;
        $product->product_name = $request->product_name;
        $product->short_desc = $request->short_desc;
        $product->long_desc = $request->long_desc;
        $product->discount_price = $request->discount_price;
        $product->product_price = $request->product_price;
        $product->quantity = $request->quantity;
        $product->size = $request->size;
        $product->status = $request->status;
        $product->uploaded_by = Auth::user()->id;

        $product->save();

        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $product = Product::find($id);
        return response()->json($product);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $product = Product::find($id);
        $imageUrl = '';
        if ($file = $request->file('product_image')) {
            $fileName = date("YmdHis")."_".$file->getClientOriginalName();
            $directory = 'admin/images/product_images/';
            $imageUrl = $directory.$fileName;
            $file->move($directory, $fileName);
            $product->image = $imageUrl;
        }
        if ($request->file('gallery_image')) {
            foreach ($request->file('gallery_image') as $image) {
                $fileName = $image->getClientOriginalName();
                $directory = 'admin/images/product_images/';
                $g_imageUrl = $directory.$fileName;
                $image->move($directory, $fileName);
                $data[] = $g_imageUrl;
            }
            $product->gallery_image = json_encode($data);
        }
        $product->cat_id = $request->cat_id;
        $product->brand_id = $request->brand_id;
        $product->product_name = $request->product_name;
        $product->short_desc = $request->short_desc;
        $product->long_desc = $request->long_desc;
        $product->discount_price = $request->discount_price;
        $product->product_price = $request->product_price;
        $product->quantity = $request->quantity;
        $product->size = $request->size;
        $product->status = $request->status;
        
        $product->save();

        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Product::find($id)->delete();

        return back();
    }
}

resources/views/admin/product/add-product.blade.php
<div class="modal fade" id="addProductModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Tambah Produk</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <form id="addProductForm" method="post" action="{{ route('product.store') }}" enctype="multipart/form-data">
                @csrf
                <div class="modal-body">
                    <div class="form-group">
                        <label for="product_status">Kategori</label>
                        <select class="form-control" name="cat_id" id="product_cat">
                            <option value="">Pilih Kategori</option>
                            @foreach($category as $categories)
                                <option value="{{$categories->id}}">{{$categories->cat_name}}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="product_status">Brand</label>
                        <select class="form-control" name="brand_id" id="product_brand">
                            <option value="">Pilih Brand</option>
                            @foreach($brand as $brands)
                                <option value="{{$brands->id}}">{{$brands->brand_name}}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="product_name">Nama Produk</label>
                        <input type="text" name="product_name" class="form-control" id="product_name" placeholder="Masukkan Nama Produk" required>
                    </div>
                    <div class="form-group">
                        <label for="short_desc">Deskripsi Pendek</label>
                        <textarea class="form-control" name="short_desc" id="short_desc" placeholder="Masukkan Deskripsi Pendek Produk"></textarea>
                    </div>
                    <div class="form-group">
                        <label for="long_desc">Deskripsi Panjang</label>
                        <textarea class="form-control" name="long_desc" id="long_desc" placeholder="Masukkan Deskripsi Panjang Produk"></textarea>
                    </div>
                    <div class="form-group">
                        <label for="discount_price">Diskon Harga</label>
                        {{--<input type="text" name="discount_price" class="form-control" id="discount_price" placeholder="Masukkan Harga Diskon">--}}
                        <div class="input-group mb-2 mr-sm-2">
                            <div class="input-group-prepend">
                                <div class="input-group-text">Rp.</div>
                            </div>
                            <input type="text" class="form-control" name="discount_price" id="discount_price" placeholder="Harga Diskon">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="product_price">Harga Produk</label>
                        {{--<input type="text" name="product_price" class="form-control" id="product_price" placeholder="Masukkan Harga Produk">--}}
                        <div class="input-group mb-2 mr-sm-2">
                            <div class="input-group-prepend">
                                <div class="input-group-text">Rp.</div>
                            </div>
                            <input type="text" class="form-control" name="product_price" id="product_price" placeholder="Harga Produk">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="quantity">Kuantitas</label>
                        <input type="number" name="quantity" class="form-control" id="quantity" placeholder="Masukkan Total Quantitas">
                    </div>
                    <div class="form-group">
                        <label for="product_size">Ukuran</label>
                        <select class="form-control" name="size" id="product_size">
                            <option value="">Pilih Ukuran</option>
                            <option value="s">S</option>
                            <option value="m">M</option>
                            <option value="l">L</option>
                            <option value="xl">XL</option>
                            <option value="xxl">XXL</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="filePhoto">Produk Image</label>
                        <input type="file" name="product_image" class="form-control-file" id="filePhoto4" onchange="preview_image(event)">
                        <img src="" id="previewHolder" width="150px">
                    </div>
                    <div class="form-group">
                        <label for="filePhoto">Galeri Image</label>
                        <input type="file" name="gallery_image[]" class="form-control-file" id="filePhoto3" multiple>
                    </div>
                    <div class="form-group">
                        <label for="product_status">Status Publikasi</label>
                        <select class="form-control" name="status" id="product_status">
                            <option value="1">Published</option>
                            <option value="0">Unpublished</option>
                        </select>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Tambah Produk</button>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/admin/product/edit-product.blade.php
<div class="modal fade" id="editProductModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Update Produk</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <form id="updateProductForm" method="post" action="" enctype="multipart/form-data">
                @csrf
                @method('put')
                <div class="modal-body">
                    <div class="form-group">
                        <label for="product_status">Kategori</label>
                        <select class="form-control" name="cat_id" id="e_product_cat">
                            <option>Select Category</option>
                            @foreach($category as $categories)
                                <option value="{{$categories->id}}">{{$categories->cat_name}}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="product_status">Brand</label>
                        <select class="form-control" name="brand_id" id="e_product_brand">
                            <option>Select Brand</option>
                            @foreach($brand as $brands)
                                <option value="{{$brands->id}}">{{$brands->brand_name}}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="e_product_name">Nama Produk</label>
                        <input type="text" name="product_name" class="form-control" id="e_product_name" required>
                    </div>
                    <div class="form-group">
                        <label for="e_short_desc">Deskripsi Pendek</label>
                        <textarea class="form-control" name="short_desc" id="e_short_desc" placeholder="Enter Product Short Description"></textarea>
                    </div>
                    <div class="form-group">
                        <label for="e_long_desc">Deskripsi Panjang</label>
                        <textarea class="form-control" name="long_desc" id="e_long_desc" placeholder="Enter Product Long Description"></textarea>
                    </div>
                    <div class="form-group">
                        <label for="e_discount_price">Harga Diskon</label>
                        <div class="input-group mb-2 mr-sm-2">
                            <div class="input-group-prepend">
                                <div class="input-group-text">Rp.</div>
                            </div>
                            <input type="text" class="form-control" name="discount_price" id="e_discount_price" placeholder="Discount price">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="e_product_price">Harga Produk</label>
                        <div class="input-group mb-2 mr-sm-2">
                            <div class="input-group-prepend">
                                <div class="input-group-text">Rp.</div>
                            </div>
                            <input type="text" class="form-control" name="product_price" id="e_product_price" placeholder="Product price">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="e_quantity">Quantitas</label>
                        <input type="number" name="quantity" class="form-control" id="e_quantity" placeholder="Enter Total quantity">
                    </div>
                    <div class="form-group">
                        <label for="product_size">Ukuran</label>
                        <select class="form-control" name="size" id="e_product_size">
                            <option>Pilih Ukuran</option>
                            <option value="s">S</option>
                            <option value="m">M</option>
                            <option value="l">L</option>
                            <option value="xl">XL</option>
                            <option value="xxl">XXL</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="filePhoto1">Produk Image</label>
                        <input type="file" name="product_image" class="form-control-file" id="filePhoto1" onchange="preview_image(event)">
                        <img src="" id="previewHolder" width="150px">
                    </div>
                    <div class="form-group">
                        <label for="filePhoto5">Galeri Image</label>
                        <input type="file" name="gallery_image" class="form-control-file" id="filePhoto5" onchange="preview_image(event)" multiple>
                    </div>
                    <div class="form-group">
                        <label for="product_status">Status Publikasi</label>
                        <select class="form-control" name="status" id="e_product_status">
                            <option value="1">Published</option>
                            <option value="0">Unpublished</option>
                        </select>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Update Produk</button>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/admin/product/product.blade.php
@extends('admin.master')
@section('body')
    <div class="content-wrapper">
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Halaman Produk</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{{ route('home') }}">Home</a></li>
                            <li class="breadcrumb-item active">Produk</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
            @if(session('message'))
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-12">
                            <div class="alert alert-success alert-dismissible fade show" role="alert">
                                {{ session('message') }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        </div>
                    </div>
                </div><!-- /.container-fluid -->
            @endif
        </section>

        <section class="content">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <span class="h4">Daftar Produk</span>
                            <button class="btn btn-primary float-right" data-toggle="modal" data-target="#addProductModal">
                                <i class="fa fa-plus"><b> Tambah Produk</b></i>
                            </button>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            <table id="productDatatable" class="table table-bordered table-striped">
                                <thead>
                                <tr>
                                    <th>No.</th>
                                    <th>Kategori</th>
                                    <th>Brand</th>
                                    <th>Nama Produk</th>
                                    <th>Harga</th>
                                    <th>Image</th>
                                    <th>Status</th>
                                    <th>Uploaded_by</th>
                                    <th>Aksi</th>
                                </tr>
                                </thead>
                                <tbody>
                                    @php($sl = 1)
                                    @foreach($product as $products)
                                    @if(Auth::user()->id == 1)
                                    <tr>
                                        <td>{{$sl++}}</td>
                                        <td>{{$products->cat_name}}</td>
                                        <td>{{$products->brand_name}}</td>
                                        <td>{{$products->product_name}}</td>
                                        <td>Rp. {{$products->product_price}}</td>
                                        <td>
                                            <img src="{{asset($products->image)}}" height="100px" alt="image">
                                        </td>
                                        <td>{{$products->status=='1'?'Active':'Inactive'}}</td>
                                        <td>{{$products->name}}</td>
                                        <td>
                                            <a href="#viewProductModal" class="btn btn-info" data-toggle="modal">
                                                <i class="fa fa-eye"></i>
                                            </a>
                                            <a href="#editProductModal" id="{{$products->id}}" class="edit btn btn-success" title="Edit">
                                                <i class="fa fa-edit"></i>
                                            </a>
                                            
                                            <form action="{{route('product.destroy',$products->id)}}" method="post">
                                                @csrf
                                                @method('DELETE')
                                                <button type="submit" class="btn btn-danger"><i class="fa fa-trash"></i></button>
                                            </form>
                                        </td>
                                    </tr>
                                    @elseif($products->uploaded_by == Auth::user()->id)
                                    <tr>
                                        <td>{{$sl++}}</td>
                                        <td>{{$products->cat_name}}</td>
                                        <td>{{$products->brand_name}}</td>
                                        <td>{{$products->product_name}}</td>
                                        <td>Rp. {{$products->product_price}}</td>
                                        <td>
                                            <img src="{{asset($products->image)}}" height="100px" alt="image">
                                        </td>
                                        <td>{{$products->status=='1'?'Active':'Inactive'}}</td>
                                        <td>{{$products->name}}</td>
                                        <td>
                                            
                                            <a href="#editProductModal" id="{{$products->id}}" class="edit btn btn-success" title="Edit">
                                                <i class="fa fa-edit"></i>
                                            </a>
                                            
                                            <form action="{{route('product.destroy',$products->id)}}" method="post">
                                                @csrf
                                                @method('DELETE')
                                                <button type="submit" class="btn btn-danger"><i class="fa fa-trash"></i></button>
                                            </form>
                                        </td>
                                    </tr>
                                    @endif
                                    @endforeach
                                </tbody>
                                
                            </table>
                        </div>
                        <!-- /.card-body -->
                    </div>
                </div>
            </div>
        </section>
    </div>
    
    {{--Add Product modal here--}}
    @include('admin.product.add-product')

    {{--Edit Product modal here--}}
    @include('admin.product.edit-product')
    
   

@endsection
@push('script')

    <script>
        $(document).ready( function () {
            //for datatable
            $('#productDatatable').DataTable();

            //show data for edit modal
            $(document).on('click', '.edit', function(e){
                $('#editProductModal').modal('show');
                e.preventDefault();
                var id = $(this).attr('id');
                $.ajax({
                    url: "{{url('admin/product')}}/"+id,
                    method: "GET",
                    success: function(data){
                        console.log(data);
                            
                            $('#e_product_cat').val(data.cat_id);
                            $('#e_product_brand').val(data.brand_id);
                            $('#e_product_name').val(data.product_name);
                            $('#e_short_desc').val(data.short_desc);
                            $('#e_long_desc').val(data.long_desc);
                            $('#e_discount_price').val(data.discount_price);
                            $('#e_product_price').val(data.product_price);
                            $('#e_quantity').val(data.quantity);
                            $('#e_product_size').val(data.size);
                            $('#e_product_status').val(data.status);

                            $('#updateProductForm').attr('action', 'product/'+id);
                    }
                })
            });
        });
    </script>

@endpush