routes/web.php
<?php

Route::get('/','HomeController@index')->name('homepage');
//Route::get('/all-category','MainController@getCategories');
//Route::get('/all-brand','MainController@getBrands');
//Route::get('/featured-product','MainController@getFeaturedProducts');
//Route::get('/new-product','MainController@getNewProducts');
//Route::get('/category/{id}','MainController@getCatProducts');
//Route::get('/product-details/{id}','MainController@getProductDetails');

//Route::post('/search-checkbox','MainController@getProductCheckbox');
//Route::post('/search-product','MainController@getProductSearch');

//Route::get('/product-comment/{productId}','MainController@getProductComment');
//Route::post('/product-comment','MainController@productComment');

//Route::post('/add-cart','CartController@addToCart');
//Route::post('/delete-cart','CartController@deleteCart');
//Route::post('/update-cart','CartController@updateCart');
//Route::get('/all-cart','CartController@allCart');
//Route::get('/count-cart','CartController@countCart');

//Route::post('/user-register','CustomerController@register');
//Route::post('/user-login','CustomerController@login');
//Route::get('/user-logout','CustomerController@logout');
//Route::get('/customer-session','CustomerController@sessionData');

//Route::post('/shipping-info','OrderController@shippingInfo');
//Route::post('/confirm-order','OrderController@confirmOrder');

//Route::get('stripe', 'OrderController@stripe');
//Route::post('stripe', 'OrderController@stripePost')->name('stripe.post');

Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix'=>'admin','namespace'=>'Backend', 'middleware'=>'auth'], function (){
    //category
    Route::get('/category','CategoryController@index')->name('admin.category');
    Route::get('/category/getTableData','CategoryController@get')->name('admin.category.getTableData');
    Route::get('/category/edit/{id}','CategoryController@edit')->name('admin.category.getEditData');
    Route::post('/category/inlineedit','CategoryController@inlineEdit')->name('admin.category.inlineEdit');
    Route::post('/category','CategoryController@create');
    Route::post('/category/update','CategoryController@update')->name('admin.category.update');
    Route::get('/category/delete/{id}','CategoryController@delete')->name('admin.category.delete');
    Route::get('/category/publish/{id}','CategoryController@publish')->name('category.publish');
    Route::get('/category/unpublish/{id}','CategoryController@unpublish')->name('category.unpublish');

    //brand
    Route::get('/brand','BrandController@index')->name('admin.brand');
    Route::post('/brand','BrandController@create');
    Route::post('/brand/update/{id}','BrandController@update')->name('admin.brand.update');
    Route::get('/brand/delete/{id}','BrandController@delete')->name('admin.brand.delete');
    Route::get('/brand/publish/{id}','BrandController@publish')->name('brand.publish');
    Route::get('/brand/unpublish/{id}','BrandController@unpublish')->name('brand.unpublish');

    //product
    Route::resource('product', 'ProductController');

    //order
    Route::get('/order','OrderController@index')->name('admin.order');
    Route::get('/order/details/{id}','OrderController@viewOrderDetails')->name('view-order-details');
    Route::get('/order/invoice/{id}','OrderController@orderInvoice')->name('order.invoice');
    Route::get('/order/export-pdf/{id}','OrderController@orderExportPdf')->name('order.export.pdf');

    //user
    Route::get('/user','UserController@index')->name('admin.user');
    Route::post('/user','UserController@create');

});


//Route::get('{path}','MainController@index')->where( 'path', '.*' );

resources/views/admin/includes/aside.blade.php
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="{{ Route('homepage') }}" class="brand-link">
        <img src="{{asset('/admin/images')}}/logo.png"
             alt="PLAINSTORE.CO"
             class="brand-image img-circle elevation-3"
             style="opacity: .8">
        <span class="brand-text font-weight-light">Plain Store.co</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <!-- <div class="image">
                <img src="{{ asset('admin/images') }}/logo.png" class="img-circle elevation-2" alt="User Image">
            </div> -->
            <div class="info">
                <a href="#" class="d-block">{{Auth::user()->name}}</a>
            </div>
        </div>

        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <!-- Add icons to the links using the .nav-icon class
                     with font-awesome or any other icon font library -->

                <li class="nav-item has-treeview">
                    <a href="{{route('home')}}" class="nav-link">
                        <i class="nav-icon fa fa-home"></i>
                        <p>
                            Dashboard
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{route('product.index')}}" class="nav-link">
                        <i class="nav-icon ion ion-bag"></i>
                        <p>
                            Produk
                        </p>
                    </a>
                </li>
                @if(Auth::user()->role == '1')
                <li class="nav-item">
                    <a href="{{route('admin.category')}}" class="nav-link">
                        <i class="nav-icon fa fa-search"></i>
                        <p>
                            Kategori
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{route('admin.brand')}}" class="nav-link">
                        <i class="nav-icon fa fa-tag"></i>
                        <p>
                            Brand
                        </p>
                    </a>
                </li>
                
                <li class="nav-item">
                    <a href="{{route('admin.order')}}" class="nav-link">
                        <i class="nav-icon ion ion-pie-graph"></i>
                        <p>
                            Pesanan
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{route('admin.user')}}" class="nav-link">
                        <i class="nav-icon ion ion-person"></i>
                        <p>
                            Pengguna
                        </p>
                    </a>
                </li>
                @endif

            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>

resources/views/admin/includes/footer.blade.php
<!-- <footer class="main-footer">
    <div class="float-right d-none d-sm-block">
        <b>Version</b> 3.0.0-alpha
    </div>
    <strong>Copyright &copy; 2014-2019 <a href="http://adminlte.io">AdminLTE.io</a>.</strong> All rights
    reserved.
</footer> -->

resources/views/admin/includes/navbar.blade.php
<nav class="main-header navbar navbar-expand bg-dark navbar-dark border-bottom">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#"><i class="fa fa-bars"></i></a>
        </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto ion ion-dark">
        <!-- Messages Dropdown Menu -->
       <!--  <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="fas fa-comments"></i>
                
            </a>
        </li>
        Notifications Dropdown Menu
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="fas fa-bell"></i>
                
            </a>
        </li> -->
        <li class="nav-item">
            <a class="nav-link" href="{{route('logout')}}"
               onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                <i class="fas fa-sign-out-alt"></i>
            </a>

            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                @csrf
            </form>
        </li>
    </ul>
</nav>